//
//  StudentInformation.swift
//  OnTheMap
//
//  Created by Edward Morton on 6/30/19.
//  Copyright © 2019 Edward Morton. All rights reserved.
//

// MARK: StudentInformation Struct

struct StudentInformation {

	// MARK: - Properties

	var objectId:	String? // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
	let uniqueKey:	String? // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
	let firstName:	String? // the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app
	let lastName:	String? // the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app
	let mapString:	String? // the location string used for geocoding the student location
	let mediaURL:	String? // the URL provided by the student
	let latitude:	Double? // the latitude of the student location (ranges from -90 to 90)
	let longitude:	Double? // the longitude of the student location (ranges from -180 to 180)
	var createdAt:	String? // DATE: the date when the student location was created
	var updatedAt:	String? // DATE: the date when the student location was last updated
	var acl:		String? // ACL: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry

	// MARK: - Initializer

	init(dictionary: [String:AnyObject]) {
		objectId	= dictionary["objectId"] as? String ?? ""
		uniqueKey	= dictionary["uniqueKey"] as? String ?? ""
		firstName	= dictionary["firstName"] as? String ?? ""
		lastName	= dictionary["lastName"] as? String ?? ""
		mapString	= dictionary["mapString"] as? String ?? ""
		mediaURL	= dictionary["mediaURL"] as? String ?? ""
		latitude	= dictionary["latitude"] as? Double ?? 0.0
		longitude	= dictionary["longitude"] as? Double ?? 0.0
		createdAt	= dictionary["createdAt"] as? String ?? ""
		updatedAt	= dictionary["updatedAt"] as? String ?? ""
		acl			= dictionary["acl"] as? String ?? ""
	}
}
